name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: checkout code
        uses: actions/checkout@v2

        # https://github.com/docker/setup-qemu-action
      -
        name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v1.0.1
        with:
          image: tonistiigi/binfmt:latest
          platforms: all

      # https://github.com/docker/setup-buildx-action
      -
        name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1.1.1

      -
        name: login to docker hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      -
        name: build the image
        run: |
          docker buildx build --push \
            --tag bsingh1904/request-bin-services:latest \
            --platform linux/amd64,linux/arm64 .